### Create a device
POST http://localhost:8080/api/devices/connect
Content-Type: application/json
Cache-Control: no-cache

{
  "name" : "iot-test-device",
  "password": "1234"
}

### Get em all (Pokemon)
GET http://localhost:8080/api/devices/
Accept: */*
Cache-Control: no-cache

###
POST http://localhost:8080/api/devices/authenticate
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "iot-test-device",
  "password": "1234"
}
###
PUT http://localhost:8080/api/devices/34d9b1a8-e5ad-4b0d-a7bc-913f642c5268/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzNGQ5YjFhOC1lNWFkLTRiMGQtYTdiYy05MTNmNjQyYzUyNjgiLCJpYXQiOjE2MDQwOTIzMDYsImV4cCI6MTYwNDY5NzEwNn0.7sDJ8fwGJQ66br1oMkcr_faNFlJjZI2ffIL5aZBlBtYIPX89G1F22-lz5mLCwujmPTdxoI7SQvmmfSp09kYbOQ

{
  "name": "string",
  "pollId": "6f29caca-8f20-4894-bedd-cbbbd2005b9c"
}

###
POST http://localhost:8080/api/devices/34d9b1a8-e5ad-4b0d-a7bc-913f642c5268/vote/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzNGQ5YjFhOC1lNWFkLTRiMGQtYTdiYy05MTNmNjQyYzUyNjgiLCJpYXQiOjE2MDQwOTIzMDYsImV4cCI6MTYwNDY5NzEwNn0.7sDJ8fwGJQ66br1oMkcr_faNFlJjZI2ffIL5aZBlBtYIPX89G1F22-lz5mLCwujmPTdxoI7SQvmmfSp09kYbOQ

{
  "yes": 5,
  "no": 10
}

###

GET http://localhost:8080/api/polls/17ac2f53-84ab-4010-a80f-1598ee7ddfe5/result
Accept: application/json
