# Create a new user to authenticate
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json
Cache-Control: no-cache

{
  "email": "kenneth@mail.com",
  "password" : "test123",
  "firstname": "Kenneth",
  "lastname": "Fossen"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json
Cache-Control: no-cache

{
"email": "ke@mail.com",
"password" : "test123",
"firstname": "Kenneth",
"lastname": "Fossen"
}


###
# Get its profile
###
GET http://localhost:8080/api/users/

###
# Authentitcate the user you created
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json
Cache-Control: no-cache

{
  "email": "ke@mail.com",
  "password" : "test123"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json
Cache-Control: no-cache

{
  "email": "admin@pollhub.no",
  "password" : "admin"
}

###
DELETE http://localhost:8080/api/users/eb4216c6-43e3-4752-bd70-309fbb405192
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzNDMxNjNmYi0xOTUyLTQ3NWEtYTIyOS0yNzBlY2Y0MGY5NzAiLCJpYXQiOjE2MDQ4Njg0NTYsImV4cCI6MTYwNTQ3MzI1Nn0.07XH_Fnb9srqaEwaMkYCvobK2IQ49-MxCweBMwryyLVZxePnQBkvTn_FXcftwPiD1DggOMzpQXzV6BR4vGNrnw
