#### Fetch a user to get an profile id
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "kenneth@mail.com",
  "password": "test123"
}

###
POST http://localhost:8080/api/polls/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MmZkY2Y5OC0xYWZiLTQ0YzUtYWM2Ni1iZTA4MWQzMzdmNjYiLCJpYXQiOjE2MDM5MDI0MzMsImV4cCI6MTYwNDUwNzIzM30.4Z5J7-A84o6QCrnRNF84JoYJRF7Y9OL92RL6seVB7SWC7d_fsrk4swWSh-3SSlAkMpeBFDYMnaeiuKjFFkdAgA

{
"access": "PUBLIC",
"answerno": "stringed",
"answeryes": "stringa",
"name": "StringyStringString",
"question": "stringy?",
"timeend": "2020-10-22T21:54:07.062Z"
}


###
GET http://localhost:8080/api/polls/

###

GET http://localhost:8080/api/polls/b85c4978-8be6-446f-ba3c-226ea61d6c55/
Cache-Control: no-cache

### You cannot vote twice

POST http://localhost:8080/api/users/2f8ed7eb-089e-4582-a2be-b78f3f4f85e6/vote/d737a0b1-7781-4fdf-ad9d-271c20783e28
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer <token>

{
  "answer": true
}


###
POST http://localhost:8080/api/polls/1aee56d8-7224-4614-8c7b-19867203d1c4/vote/
Content-Type: application/json
Cache-Control: no-cache

{
"answer" : false
}