#### Fetch a user to get an profile id
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "kenneth@mail.com",
  "password": "test123"
}

###
POST http://localhost:8080/api/polls/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzZGNmODdlYS02MjNmLTQ4ZTYtOGE2OS03YTdjN2E0MDhiMzUiLCJpYXQiOjE2MDM4MjQzODYsImV4cCI6MTYwNDQyOTE4Nn0.PnAkPMTDLBPUuBxQ1S84l6Y8xSsJZBR2kxbQHJ7qYnFqEGUpZ568J7o1hJ12bk21iwd2DJ8-sKPtUizIVrgJIQ

{
"access": "PUBLIC",
"answerno": "stringed",
"answeryes": "stringa",
"name": "StringyStringString",
"question": "stringy?",
"timeend": "2020-10-22T21:54:07.062Z"
}


###
GET http://localhost:8080/api/polls/

###

POST http://localhost:8080/api/polls/26ad59e2-4ea4-4aab-b0a6-e6d4e32af38e/vote/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzZGNmODdlYS02MjNmLTQ4ZTYtOGE2OS03YTdjN2E0MDhiMzUiLCJpYXQiOjE2MDM4MjQzODYsImV4cCI6MTYwNDQyOTE4Nn0.PnAkPMTDLBPUuBxQ1S84l6Y8xSsJZBR2kxbQHJ7qYnFqEGUpZ568J7o1hJ12bk21iwd2DJ8-sKPtUizIVrgJIQ

{
  "answer": false
}

### You cannot vote twice

POST http://localhost:8080/api/users/2f8ed7eb-089e-4582-a2be-b78f3f4f85e6/vote/d737a0b1-7781-4fdf-ad9d-271c20783e28
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer <token>

{
  "answer": true
}