#### Fetch a user to get an profile id
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "kenneth@mail.com",
  "password": "newpassword"
}

###
GET http://localhost:8080/api/polls/

###

POST http://localhost:8080/api/polls/2a80286a-65fd-4c41-8f0a-e0dc79a48427/vote/
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2IxOTQxZi0xYjBhLTQ0OTQtYjAxYy0xMjBjYzBjMjQ2YzAiLCJpYXQiOjE2MDM3NjEzOTIsImV4cCI6MTYwNDM2NjE5Mn0.rUWQVFXgHOu4J8H27zKz4jWbyk823K-yHyL3hIZ_86d1dIY8xwSonwJQ1NRH6ug0Diavu0286-ngbgnD0IFkag

{
  "answer": false
}

### You cannot vote twice

POST http://localhost:8080/api/users/2f8ed7eb-089e-4582-a2be-b78f3f4f85e6/vote/d737a0b1-7781-4fdf-ad9d-271c20783e28
Content-Type: application/json
Cache-Control: no-cache
Authorization: Bearer <token>

{
  "answer": true
}